function handle(v){if(!v)return null;return String(v).replace(/^https?:\/\/(www\.)?/,'').replace(/\/$/,'').split('/').filter(Boolean).pop()}
async function json(url,opts={}){const r=await fetch(url,opts);const t=await r.text();let b;try{b=JSON.parse(t)}catch{b=null}if(!r.ok)throw Error('Upstream '+r.status);return b}
const iso=s=>s?new Date(Number(s)*1000).toISOString():null;
async function github(input){const u=handle(input);const h={Accept:'application/vnd.github+json','User-Agent':'CareerOS'};const [x,repos,events]=await Promise.all([json('https://api.github.com/users/'+encodeURIComponent(u),{headers:h}),json('https://api.github.com/users/'+encodeURIComponent(u)+'/repos?per_page=100&sort=updated',{headers:h}),json('https://api.github.com/users/'+encodeURIComponent(u)+'/events/public?per_page=100',{headers:h})]);const langs={};repos.forEach(r=>r.language&&(langs[r.language]=(langs[r.language]||0)+1));return {summary:u+' • '+x.public_repos+' public repos • '+x.followers+' followers',profile:{login:x.login,name:x.name,avatar:x.avatar_url,bio:x.bio,location:x.location,company:x.company,blog:x.blog,publicRepos:x.public_repos,publicGists:x.public_gists,followers:x.followers,following:x.following,createdAt:x.created_at},metrics:['Public repos: '+x.public_repos,'Followers: '+x.followers,'Following: '+x.following,'Public gists: '+x.public_gists,'Public events fetched: '+events.length,'Latest public activity: '+(events[0]?.created_at||'none')],languages:Object.entries(langs).map(([name,count])=>({name,count})),source:'https://github.com/'+u,updatedAt:new Date().toISOString(),repos:repos.slice(0,20).map(r=>({name:r.name,fullName:r.full_name,description:r.description,stars:r.stargazers_count,forks:r.forks_count,language:r.language,updated:r.updated_at,htmlUrl:r.html_url})),events:events.slice(0,20).map(e=>({type:e.type,repo:e.repo?.name||'',createdAt:e.created_at}))}}
async function codeforces(input){const u=handle(input);const [i,s,r]=await Promise.all([json('https://codeforces.com/api/user.info?handles='+encodeURIComponent(u)),json('https://codeforces.com/api/user.status?handle='+encodeURIComponent(u)+'&from=1&count=100'),json('https://codeforces.com/api/user.rating?handle='+encodeURIComponent(u))]);const x=i.result[0],a=s.result||[],rh=r.result||[];const v={},l={},uniq=new Set();a.forEach(z=>{v[z.verdict]=(v[z.verdict]||0)+1;l[z.programmingLanguage]=(l[z.programmingLanguage]||0)+1;if(z.problem?.contestId&&z.problem?.index)uniq.add(z.problem.contestId+'-'+z.problem.index)});return {summary:x.handle+' • rating '+(x.rating??'unrated')+' • '+(x.rank??'unrated'),profile:{handle:x.handle,avatar:x.avatar,titlePhoto:x.titlePhoto,firstName:x.firstName,lastName:x.lastName,country:x.country,city:x.city,organization:x.organization,rating:x.rating,maxRating:x.maxRating,rank:x.rank,maxRank:x.maxRank,contribution:x.contribution,friendOfCount:x.friendOfCount,registrationTime:iso(x.registrationTimeSeconds),lastOnlineTime:iso(x.lastOnlineTimeSeconds)},metrics:['Rating: '+(x.rating??'unrated'),'Max rating: '+(x.maxRating??'—'),'Rank: '+(x.rank??'—'),'Max rank: '+(x.maxRank??'—'),'Submissions fetched: '+a.length,'Accepted in fetched submissions: '+a.filter(z=>z.verdict==='OK').length,'Unique problems in fetched submissions: '+uniq.size,'Last submission: '+(iso(a[0]?.creationTimeSeconds)||'none')],submissionStats:{verdicts:Object.entries(v).map(([name,count])=>({name,count})),languages:Object.entries(l).map(([name,count])=>({name,count}))},recentSubmissions:a.slice(0,30).map(z=>({contestId:z.problem?.contestId,index:z.problem?.index,name:z.problem?.name,verdict:z.verdict,language:z.programmingLanguage,createdAt:iso(z.creationTimeSeconds)})),ratingHistory:rh.slice(-30).map(z=>({name:z.contestName,newRating:z.newRating,oldRating:z.oldRating,createdAt:iso(z.ratingUpdateTimeSeconds)})),source:'https://codeforces.com/profile/'+u,updatedAt:new Date().toISOString()}}
async function leetcode(input){const u=handle(input);const q=`query($username:String!){allQuestionsCount{difficulty count} matchedUser(username:$username){username profile{realName aboutMe userAvatar ranking reputation skillTags} submitStats{acSubmissionNum{difficulty count submissions}} submissionCalendar languageProblemCount{languageName problemsSolved} badges{id displayName icon creationDate}} recentAcSubmissionList(username:$username,limit:30){title titleSlug timestamp}}`;const x=await json('https://leetcode.com/graphql',{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://leetcode.com','User-Agent':'Mozilla/5.0'},body:JSON.stringify({query:q,variables:{username:u}})});if(x.errors?.length)throw Error(x.errors.map(e=>e.message).join('; '));const m=x.data?.matchedUser;if(!m)throw Error('User not found or profile is not public');const a=m.submitStats?.acSubmissionNum||[],all=Number(a.find(z=>z.difficulty==='All')?.count||0),subs=Number(a.find(z=>z.difficulty==='All')?.submissions||0),tot=(x.data.allQuestionsCount||[]);const cal=typeof m.submissionCalendar==='string'?JSON.parse(m.submissionCalendar||'{}'):(m.submissionCalendar||{});const ce=Object.entries(cal).map(([t,c])=>({date:new Date(Number(t)*1000).toISOString().slice(0,10),count:Number(c)})).sort((a,b)=>a.date.localeCompare(b.date));let max=0,st=0,prev=null;for(const d of ce.filter(x=>x.count>0)){const cur=new Date(d.date+'T00:00:00Z');st=prev&&Math.round((cur-prev)/86400000)===1?st+1:1;max=Math.max(max,st);prev=cur}const diff=['Easy','Medium','Hard'].map(d=>({difficulty:d,solved:Number(a.find(z=>z.difficulty===d)?.count||0),submissions:Number(a.find(z=>z.difficulty===d)?.submissions||0),total:Number(tot.find(z=>z.difficulty===d)?.count||0)}));return {summary:m.username+' • '+all+' solved • rank '+(m.profile?.ranking??'—'),profile:{username:m.username,realName:m.profile?.realName,about:m.profile?.aboutMe,avatar:m.profile?.userAvatar,ranking:m.profile?.ranking,reputation:m.profile?.reputation,skillTags:m.profile?.skillTags||[]},metrics:['Solved: '+all,'Easy: '+(a.find(z=>z.difficulty==='Easy')?.count||0),'Medium: '+(a.find(z=>z.difficulty==='Medium')?.count||0),'Hard: '+(a.find(z=>z.difficulty==='Hard')?.count||0),'Total submissions: '+subs,'Ranking: '+(m.profile?.ranking??'—'),'Active days in public calendar: '+ce.filter(x=>x.count>0).length,'Max streak from public calendar: '+max],difficulty:diff,languages:(m.languageProblemCount||[]).map(z=>({name:z.languageName,count:Number(z.problemsSolved||0)})),calendar:ce.slice(-370),badges:(m.badges||[]).map(z=>({name:z.displayName,icon:z.icon,date:z.creationDate})),recentAccepted:(x.data.recentAcSubmissionList||[]).map(z=>({title:z.title,slug:z.titleSlug,createdAt:iso(z.timestamp)})),source:'https://leetcode.com/u/'+u+'/',updatedAt:new Date().toISOString()}}
async function pageProfile(input,site,source){const u=handle(input);const url=input.startsWith('http')?input:source+u+'/';const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html,application/xhtml+xml'}});const html=await r.text();const text=html.replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();if(!r.ok)throw Error('Upstream '+r.status);return {summary:u+' • public profile',profile:{username:u},metrics:['Public profile reachable: yes'],source:url,updatedAt:new Date().toISOString(),limitation:'Only publicly accessible page data is reported; private analytics are not guessed.',rawPreview:text.slice(0,500)}}
async function codechef(input){return pageProfile(input,'codechef','https://www.codechef.com/users/')}
async function geeksforgeeks(input){return pageProfile(input,'gfg','https://www.geeksforgeeks.org/user/')}
async function linkedin(input){
  const u=handle(input);
  const url=input.startsWith('http')?input:'https://www.linkedin.com/in/'+u+'/';
  // LinkedIn blocks server-side anonymous requests with 999/authwall.
  // Return a valid JSON result instead of exposing an HTML/server error to the UI.
  let directText='';
  try{
    const rr=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html,application/xhtml+xml'}});
    const html=await rr.text();
    if(rr.ok && html && !/authwall|sign in|join now|security verification|captcha/i.test(html)){
      directText=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
    }
  }catch(e){}
  if(directText){
    return {summary:u+' • public LinkedIn profile',profile:{username:u},metrics:['Public profile page: reachable'],source:url,updatedAt:new Date().toISOString(),rawPreview:directText.slice(0,1500),limitation:'Only information exposed on the public profile page is reported.'};
  }
  // Search-engine fallback. This is best-effort public information only.
  let snippet='';
  try{
    const q=encodeURIComponent('site:linkedin.com/in/'+u+' '+u);
    const rr=await fetch('https://www.google.com/search?q='+q+'&num=5',{headers:{'User-Agent':'Mozilla/5.0','Accept-Language':'en-US,en;q=0.9'}});
    const html=await rr.text();
    snippet=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim().slice(0,2500);
  }catch(e){}
  return {
    summary:u+' • LinkedIn public profile',
    profile:{username:u},
    metrics:snippet?['Public search representation found']:['LinkedIn public page blocked server-side (HTTP 999/authwall)'],
    source:url,
    updatedAt:new Date().toISOString(),
    publicSearchPreview:snippet||null,
    limitation:'LinkedIn does not expose reliable public profile fields to anonymous server requests. CareerOS never fabricates or bypasses private/authenticated data.'
  };
}
async function instagram(input){const u=handle(input);return {summary:'Instagram public username connected',profile:{username:u},metrics:['Username: '+u,'Post/insight analytics: requires authorized Meta API'],source:input.startsWith('http')?input:'https://www.instagram.com/'+u+'/',updatedAt:new Date().toISOString(),limitation:'Instagram analytics require authorized Meta access; private/personal data is not scraped.'}}
export default async function(req,res){const b=req.body||{};const defs={leetcode,codeforces,codechef,geeksforgeeks,github,linkedin,instagram};const out={};for(const [k,fn] of Object.entries(defs)){if(!b[k])continue;try{out[k]=await fn(b[k])}catch(e){out[k]={error:'Live source request failed.',detail:e.message}}}res.status(200).json({profiles:out,fetchedAt:new Date().toISOString(),policy:'public-source-only'})}